language: python
python:
- '3.3'
- '3.4'
- '3.5'
os:
- linux
before_install:
- openssl aes-256-cbc -K $encrypted_f8cd32dad80d_key -iv $encrypted_f8cd32dad80d_iv
  -in README.md.enc -out README.md -d
- sudo apt-get update -qq
- sudo apt-get install unity -y
- sudo apt-get install python3-tk -y
- sudo apt-get install apache2 -y
- sudo apt-get install php5 -y
install:
- pip install coveralls
before_script:
- sudo cp -f test/travis-ci-apache /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)/test?g" --in-place /etc/apache2/sites-available/default
- sudo service apache2 restart
script:
- python test.py
- coverage run --omit=test.py test.py
after_success:
- coveralls
notifications:
  email: false
